# Generated by Django 4.1 on 2022-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Larg', 'L'), ('Mediom', 'M'), ('Small', 'S'), ('Xlarg', 'XL'), ('XXLarg', 'XXL'), ('XXXLarg', 'XXXL')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product', to='Product_app.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='product', to='Product_app.size'),
        ),
    ]
