# Generated by Django 4.1 on 2022-08-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0004_productimagegallery_product_image_galeery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
