# Generated by Django 4.1 on 2022-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0005_product_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
