# Generated by Django 4.1 on 2022-09-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0011_cart_cartdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodoct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='Product_app.product')),
            ],
        ),
    ]
