# Generated by Django 4.1 on 2022-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.IntegerField()),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
