# Generated by Django 4.1 on 2022-08-29 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.timedelta(seconds=120)),
        ),
    ]
