# Generated by Django 4.1 on 2022-08-30 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0005_alter_otc_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 7, 43, 56, 677617, tzinfo=datetime.timezone.utc)),
        ),
    ]
