# Generated by Django 4.1 on 2022-08-31 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0024_alter_otc_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 12, 58, 56, 993699, tzinfo=datetime.timezone.utc)),
        ),
    ]
